// typescript/projects/vue-app/src/views/UsersView.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useUsersStore } from '@/stores/users'
import UserCard from '@/components/UserCard.vue'

const usersStore = useUsersStore()
// storeToRefs 保留響應性，同時維持型別
const { users, loading, error } = storeToRefs(usersStore)

// 本地搜尋字串（client 端過濾）
const keyword = ref('')

const filteredUsers = computed(() => {
  const q = keyword.value.trim().toLowerCase()
  if (!q) return users.value
  return users.value.filter(
    (u) =>
      u.name.toLowerCase().includes(q) ||
      u.username.toLowerCase().includes(q),
  )
})

onMounted(() => {
  usersStore.fetchUsers()
})
</script>

<template>
  <section class="users">
    <h1>使用者列表</h1>

    <input
      v-model="keyword"
      class="search"
      type="search"
      placeholder="以姓名或帳號搜尋…"
      aria-label="搜尋使用者"
    />

    <p v-if="loading" class="status">載入中…</p>
    <p v-else-if="error" class="status error">發生錯誤：{{ error }}</p>
    <p v-else-if="filteredUsers.length === 0" class="status">
      找不到符合的使用者
    </p>

    <div v-else class="list">
      <UserCard v-for="user in filteredUsers" :key="user.id" :user="user" />
    </div>
  </section>
</template>

<style scoped>
.users h1 {
  margin-top: 0;
}

.search {
  width: 100%;
  max-width: 360px;
  padding: 0.5rem 0.75rem;
  margin-bottom: 1rem;
  border: 1px solid #cbd5e1;
  border-radius: 6px;
}

.status {
  color: #64748b;
}

.status.error {
  color: #dc2626;
}

.list {
  display: grid;
  gap: 0.75rem;
}
</style>

// typescript/projects/react-app/src/views/UsersView.tsx
import { useEffect, useMemo, useState } from 'react'
import UserCard from '@/components/UserCard'
import { useUserStore } from '@/stores/useUserStore'

// 使用者列表頁：載入資料、顯示 loading / error / 列表，並提供前端搜尋
export default function UsersView() {
  const users = useUserStore((state) => state.users)
  const loading = useUserStore((state) => state.loading)
  const error = useUserStore((state) => state.error)
  const fetchUsers = useUserStore((state) => state.fetchUsers)

  // 受控輸入：搜尋關鍵字
  const [keyword, setKeyword] = useState('')

  // 掛載時載入使用者（fetchUsers 為穩定的 action 參考）
  useEffect(() => {
    void fetchUsers()
  }, [fetchUsers])

  // 依 name / username 做前端過濾；用 useMemo 避免每次 render 重算
  const filteredUsers = useMemo(() => {
    const kw = keyword.trim().toLowerCase()
    if (!kw) return users
    return users.filter(
      (user) =>
        user.name.toLowerCase().includes(kw) ||
        user.username.toLowerCase().includes(kw),
    )
  }, [users, keyword])

  return (
    <section className="users">
      <h1>使用者列表</h1>

      <input
        className="search-input"
        type="search"
        placeholder="以姓名或帳號搜尋…"
        aria-label="搜尋使用者"
        value={keyword}
        onChange={(event) => setKeyword(event.target.value)}
      />

      {loading && <p className="status">載入中…</p>}
      {error && <p className="status status-error">發生錯誤：{error}</p>}

      {!loading && !error && (
        <>
          <p className="hint">
            共 {users.length} 位使用者，顯示 {filteredUsers.length} 位
          </p>
          {filteredUsers.length === 0 ? (
            <p className="status">查無符合的使用者</p>
          ) : (
            <div className="user-grid">
              {filteredUsers.map((user) => (
                <UserCard key={user.id} user={user} />
              ))}
            </div>
          )}
        </>
      )}
    </section>
  )
}
